;; Generated by kunagi-toolbox.

(ns kunagi.appinfo)

(def
 appinfo
 {:browserapp {:js-optimizations :simple},
  :build-time "2020-04-05 13:07",
  :legal nil,
  :project {:group "Kunagi", :id "kunagi", :name "Kunagi Estimations"},
  :release {:major 2, :minor 0},
  :serverapp {:config-dir "/etc/kunagi",
              :executable-name "kunagid",
              :executable-path "/usr/local/bin/kunagid",
              :http-port 23004,
              :uri "https://kunagi.frankenburg.software",
              :user-name "kunagi",
              :vhost "kunagi.frankenburg.software",
              :working-dir "/var/local/kunagi"}})
